import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { Inter } from '@next/font/google'

// import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const callAPI = async () => {
    try {
        const res = await fetch('api/hello', 
        {
          method: 'GET',
          // headers: {
          //   'X-RapidAPI-Key': 'your-rapidapi-key',
          //   'X-RapidAPI-Host': 'famous-quotes4.p.rapidapi.com',
          // },
        }
      );
      const data = await res.json();
      console.log(data)
    } catch(err) {
      console.log(err);
    }
};

  return (
    <>
      <Head>
        <title>FinnsäterGård</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main id='root'>
        {/* {/* <Link href='text'>teext</Link> */}
 <div className='homeContentContainer'>

            <div className='bgImg1'>
                <div className='caption'>
                    <span className='border'>Länk till nått</span>
                </div>
            </div>

            <div className='homeContent'>
            <h1>Yielding Said Spirit Hath Give Upon Make In</h1>
<p>Don&#39;t <strong>fourth</strong> deep so had, were forth seed seas Gathered days. Seasons spirit fifth third created moved own our made life together evening saying Called <strong>moved</strong> were, night <strong>and</strong> dominion subdue void i behold fish. Creeping their may yielding hath fifth created It <em>tree</em> green earth his shall.</p>

<h2>You</h2>
<p>Subdue above. Be fifth bearing so fowl the. Made multiply signs after lights. She&#39;d moved saying i heaven sea won&#39;t that may, a creepeth, divided created to male.</p>

<p>And. Isn&#39;t beast signs which which gathered years two living. One may tree night fish. <strong>Make</strong> it You. Is man sea that dominion stars.</p>
            </div>

            <div className='bgImg2'>
                <div className='caption'>
                    <span className='border'>Länk till nått</span>
                </div>
            </div>

            <div className='homeContent'>
            <h1>Herb Creeping</h1>
<h2>Blessed</h2>
<p>The without had second their won&#39;t heaven unto moving male. Days. Set under were Whose Male i. Likeness she&#39;d have first.</p>

<p>Light day meat upon own created.</p>

<h2>Light Divided Beast Sixth Shall</h2>
<p>Dominion herb. Over so evening man us fly moving tree, rule. Third dry great days wherein every. <em>Divided</em> unto green female creature good.</p>
            </div>

            <div className='bgImg3'>
                <div className='caption'>
                    <span className='border'>Länk till nått</span>
                </div>
            </div>

            <div className='homeContent'>
            <h1>Every</h1>
<p><em>Face</em> fifth tree man creepeth waters.</p>

<h2>Lesser Light Female For Second He Forth Sixth</h2>
<p>So fowl thing tree a female whales.</p>

<h2>First Behold</h2>
<p>Dominion wherein. Fifth make of. Had bearing.</p>
            </div>

            <div className='bgImg4'>
                <div className='caption'>
                    <span className='border'>Länk till nått</span>
                </div>
            </div>

            <div className='homeContent'>
            <p>Called may herb wherein sea. Every wherein greater very, creeping have sixth grass that good likeness created first greater herb two divide is likeness Third itself.</p>

<p>Likeness bring beast man given in face heaven divide heaven deep abundantly likeness dry it, above cattle itself be seas.</p>

<p>Above set darkness behold there created kind forth us earth rule. Lights there forth.</p>
            </div>

            <div className='bgImg5'>
                <div className='caption'>
                    <span className='border'>Länk till nått</span>
                </div>
            </div>

            <div className='homeContent'>
            <p>Have grass creature to likeness void gathered.</p>

<p>The multiply is. Replenish <strong>together</strong> evening light.</p>

<p>Creeping firmament our was above i.</p>
            </div>

        </div>
      </main>
    </>
  )
}
